# Generated by Django 3.0.3 on 2020-02-29 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_auto_20200227_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='1234', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Password Name must be alphanumeric or contains numbers', regex='^[A-Za-z0-9.+-]*$')]),
        ),
    ]
