# Generated by Django 3.0.3 on 2020-02-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_auto_20200229_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.BigIntegerField(max_length=50)),
                ('money', models.BigIntegerField(max_length=50)),
                ('paymentMonth', models.CharField(max_length=50)),
                ('paymentDay', models.CharField(max_length=50)),
                ('paymentTime', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
    ]
