# Generated by Django 3.0.3 on 2020-02-29 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_auto_20200301_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='userId',
        ),
        migrations.AddField(
            model_name='amount',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
